AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31



Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: deckderby.StreamLambdaHandler::handleRequest
      Runtime: java17
      CodeUri: .
      Timeout: 30
      Architectures:
        - x86_64
      Events:
        Api:
          Type: Api
          Properties:
            Path: /hello
            Method: GET