version: "3"
volumes:
  postgresqldata:
services:
  db:
    image: postgres:15.1-alpine
    container_name: 'deckderby-pg'
    ports:
      - '5431:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresqldata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/A.sql